[package]
name = "ethersync"
description = "Enables real-time co-editing of local text files."
version = "0.2.0"
edition = "2021"
default-run = "ethersync"

[dependencies]
serde_json = { version = "1" }
clap = { version = "4.5.3", features = ["derive"] }
automerge = "0.5.9"
rand = "0.8.5"
tokio = { version = "1", features = ["full"] }
operational-transform = "0.6.1"
anyhow = "1.0.81"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["local-time"] }
nvim-rs = { version = "0.7.0", features = ["use_tokio"] }
temp-dir = "0.1.13"
async-trait = "0.1.79"
pretty_assertions = "1.4.0"
futures = "0.3.30"
ropey = "1.6.1"
serde = "1.0.198"
time = { version = "0.3.36", features = ["formatting"] }
time-macros = { version = "0.2.0-alpha.1" }
local-ip-address = "0.6.1"
public-ip = "0.2.2"
tokio-util = {version = "0.7.11", features = ["codec"] }
ignore = "0.4.22"
notify = "6.1.1"
dissimilar = "1.0.9"
path-clean = "1.0.1"
libp2p = { version = "0.53.2", features = ["tokio", "tcp", "noise", "yamux"]}
libp2p-stream = "0.1.0-alpha.1"
libp2p-identity = { version ="0.2.9", features = ["ed25519"] }
libp2p-pnet = "0.24.0"
memorable-wordlist = "0.1.7"
pbkdf2 = "0.12.2"
sha2 = "0.10.8"
rust-ini = "0.21.1"

[dev-dependencies]
assert_matches = "1.5"
serial_test = "3.1.1"
tracing-test = "0.2.4"

# Stripping symbols (not debuginfo) reduces binary size by ~1.5x.
# This is the default profile for `cargo install`:
# https://doc.rust-lang.org/cargo/reference/profiles.html#profile-selection.
# TODO: We may want to make [profile.release-size] the default
# once we're out of the fast iteration development phase.
[profile.release]
strip = true
opt-level = 3

# 2-3x slower to compile, but produces a ~1.2x smaller binary.
[profile.release-lto]
inherits = "release"
lto = true
codegen-units = 1

# Also quite slow to compile, but produces a ~1.6x smaller binary.
[profile.release-size]
inherits = "release"
lto = true
codegen-units = 1
opt-level = "s"
